backend = "xrender";
vsync = false;

corner-radius = 8;
rounded-corners-exclude = [
	"class_g = 'Polybar'"
]

shadow = true;
shadow-radius = 12;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.35;

inactive-opacity = 0.92;
active-opacity = 1.0;
frame-opacity = 0.9;

opacity-rule = [
	"90:class_g = 'kitty'"
]
